services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mini_siem
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports: 
      - "5423:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mini_siem"]
      interval: 5s
      timeout: 5s
      retries: 5
      

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://user:1234@db:5432/mini_siem
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"
  

volumes:
  postgres_data: